Repository fortytwoservices/terraform-azuread-entitlement-management, pull requests merged in 2024-06, with the labels that each got.

#111 Feat: allow multiple primary approvers
  .github/linters/.markdown-lint.yml
  .terraform-docs.yml
  README.md
  examples/advanced.tf
  examples/basic.tf
  main.tf
  readme-header.md
  variables.tf
Labels: enhancement

#115 fix!: updated requestor parameter options to better reflect the Terraform resources.
  README.md
  main.tf
  variables.tf
Labels: bug

#116 chore(main): release 2.0.0
  CHANGELOG.md
Labels: autorelease: pending

#117 fix: fixed broken for_each reference after restructuring the requesto…
  main.tf
Labels: bug

#118 chore(main): release 2.0.1
  CHANGELOG.md
Labels: autorelease: pending

#129 fix: updated default behaviour of requsetor_settings to specify the c…
  .terraform-docs.yml
  README.md
  _README_header.md
  examples/advanced.tf
  examples/advanced/main.tf
  examples/basic.tf
  examples/basic/main.tf
  readme-header.md
  variables.tf
Labels: bug

#126 chore(main): release 2.1.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending
