Repository fortytwoservices/terraform-azuread-entitlement-management, pull requests merged in 2024-05, with the labels that each got.

#106 fix: changed the conditional check of approval_required input paramet…
  main.tf
Labels: bug

#108 feat: added markdown lint configuration file, with md012 - multiple c…
  .github/linters/.markdown-lint.yml
Labels: enhancement

#110 feat: added reference to newly added lint configuration file
  .github/workflows/code-review.yml
Labels: enhancement

#107 chore(main): release 1.0.2
  CHANGELOG.md
Labels: autorelease: pending
